stages:
  - test

e2e test - Edge:
  image: cypress/browsers:node14.10.1-edge88
  script:
    - npm install
    - npm run cy:start:edge
  artifacts:
    when: always
    paths:
      - cypress/screenshots/**
      - cypress/videos/**
      - cypress/reports/**
    expire_in: 1 month
  only:
    refs:
      - schedules

e2e test - Chrome:
  image: cypress/browsers:node14.16.0-chrome89-ff86
  script:
    - npm install
    - npm run cy:start:chrome
  artifacts:
    when: always
    paths:
      - cypress/screenshots/**
      - cypress/videos/**
      - cypress/reports/**
    expire_in: 1 month
  only:
    refs:
      - schedules

e2e test - Firefox:
  image: cypress/browsers:node14.16.0-chrome89-ff86
  script:
    - npm install
    - npm run cy:start:firefox
  artifacts:
    when: always
    paths:
      - cypress/screenshots/**
      - cypress/videos/**
      - cypress/reports/**
    expire_in: 1 month
  only:
    refs:
      - schedules

