image: cypress/base:12
options:
  max-time: 10

definitions:
  steps:
    - step: &dependencies
        name: Install dependencies
        caches:
          - npm
          - cypress
          - node
        script:
          - npm ci
    - step: &e2eDevelop
        name: E2E develop tests and reports
        caches:
          - node
          - cypress
        script:
          - npm run reports:clean
          - ./cypress.sh develop
          - npm run reports:merge
          - npm run reports:generate
        artifacts:
          - cypress/screenshots/**
          - cypress/videos/**
          - cypress/reports/**
    - step: &e2eDevelopApi
        name: E2E develop API tests and reports
        caches:
          - node
          - cypress
        script:
          - npm run reports:clean
          - ./cypress.sh develop api
          - npm run reports:merge
          - npm run reports:generate
        artifacts:
          - cypress/screenshots/**
          - cypress/videos/**
          - cypress/reports/**
    - step: &e2eDevelopUi
        name: E2E develop UI tests and reports
        caches:
          - node
          - cypress
        script:
          - npm run reports:clean
          - ./cypress.sh develop ui
          - npm run reports:merge
          - npm run reports:generate
        artifacts:
          - cypress/screenshots/**
          - cypress/videos/**
          - cypress/reports/**
    - step: &e2eStaging
        name: E2E staging tests and reports
        caches:
          - node
          - cypress
        script:
          - npm run reports:clean
          - ./cypress.sh staging
          - npm run reports:merge
          - npm run reports:generate
        artifacts:
          - cypress/screenshots/**
          - cypress/videos/**
          - cypress/reports/**
    - step: &e2eStagingApi
        name: E2E staging API tests and reports
        caches:
          - node
          - cypress
        script:
          - npm run reports:clean
          - ./cypress.sh staging api
          - npm run reports:merge
          - npm run reports:generate
        artifacts:
          - cypress/screenshots/**
          - cypress/videos/**
          - cypress/reports/**
    - step: &e2eStagingUi
        name: E2E staging UI tests and reports
        caches:
          - node
          - cypress
        script:
          - npm run reports:clean
          - ./cypress.sh staging ui
          - npm run reports:merge
          - npm run reports:generate
        artifacts:
          - cypress/screenshots/**
          - cypress/videos/**
          - cypress/reports/**
  caches:
    npm: $HOME/.npm
    cypress: $HOME/.cache/Cypress

pipelines:
  default:
    - step:
        <<: *dependencies
    - step:
        <<: *e2eStaging
  custom:
    develop:
      - step:
          <<: *dependencies
      - step:
          <<: *e2eDevelop
    develop-api:
      - step:
          <<: *dependencies
      - step:
          <<: *e2eDevelopApi
    develop-ui:
      - step:
          <<: *dependencies
      - step:
          <<: *e2eDevelopUi
    staging:
      - step:
          <<: *dependencies
      - step:
          <<: *e2eStaging
    staging-api:
      - step:
          <<: *dependencies
      - step:
          <<: *e2eStagingApi
    staging-ui:
      - step:
          <<: *dependencies
      - step:
          <<: *e2eStagingUi
