image: cypress/base:12
options:
  max-time: 10

definitions:
  steps:
    - step: &dependencies
        name: Install dependencies
        caches:
          - npm
          - cypress
          - node
        script:
          - npm ci
    - step: &e2eDevelop
        name: E2E develop tests
        caches:
          - node
          - cypress
        script:
          - npm run reports:clean 
          - ./cypress.sh develop || true
        artifacts:
          - cypress/screenshots/**
          - cypress/videos/**
          - cypress/reports/**
    - step: &e2eDevelopApi
        name: E2E develop API tests
        caches:
          - node
          - cypress
        script:
          - npm run reports:clean 
          - ./cypress.sh develop api || true
        artifacts:
          - cypress/screenshots/**
          - cypress/videos/**
          - cypress/reports/**
    - step: &e2eDevelopUi
        name: E2E develop UI ests
        caches:
          - node
          - cypress
        script:
          - npm run reports:clean 
          - ./cypress.sh develop ui || true
        artifacts:
          - cypress/screenshots/**
          - cypress/videos/**
          - cypress/reports/**
    - step: &e2eStaging
        name: E2E staging tests
        caches:
          - node
          - cypress
        script:
          - npm run reports:clean
          - ./cypress.sh staging || true
        artifacts:
          - cypress/screenshots/**
          - cypress/videos/**
          - cypress/reports/**
    - step: &e2eStagingApi
        name: E2E staging API tests
        caches:
          - node
          - cypress
        script:
          - npm run reports:clean 
          - ./cypress.sh staging api || true
        artifacts:
          - cypress/screenshots/**
          - cypress/videos/**
          - cypress/reports/**
    - step: &e2eStagingUi
        name: E2E staging UI tests
        caches:
          - node
          - cypress
        script:
          - npm run reports:clean 
          - ./cypress.sh staging ui || true
        artifacts:
          - cypress/screenshots/**
          - cypress/videos/**
          - cypress/reports/**
    - step: &generateReport
        name: Generate report
        caches:
          - npm
          - node
        script:
          - npm run reports:merge
          - npm run reports:generate
        artifacts:
          - cypress/reports/**
  caches:
    npm: $HOME/.npm
    cypress: $HOME/.cache/Cypress

pipelines:
  default:
    - step:
        <<: *dependencies
    - step:
        <<: *e2eStaging
    - step:
        <<: *generateReport
  custom:
    develop:
      - step:
          <<: *dependencies
      - step:
          <<: *e2eDevelop
      - step:
          <<: *generateReport
    develop-api:
      - step:
          <<: *dependencies
      - step:
          <<: *e2eDevelopApi
      - step:
          <<: *generateReport
    develop-ui:
      - step:
          <<: *dependencies
      - step:
          <<: *e2eDevelopUi
      - step:
          <<: *generateReport
    staging:
      - step:
          <<: *dependencies
      - step:
          <<: *e2eStaging
      - step:
          <<: *generateReport
    staging-api:
      - step:
          <<: *dependencies
      - step:
          <<: *e2eStagingApi
      - step:
          <<: *generateReport
    staging-ui:
      - step:
          <<: *dependencies
      - step:
          <<: *e2eStagingUi
      - step:
          <<: *generateReport