version: "3.3"
services: 
  e2e:
    image: cypress
    build: .
    container_name: cypress
    command: npm run test
    volumes:
      - ./cypress:/app/cypress
      - ./cypress.json:/app/cypress.json