version: 2
jobs:
  e2e:
    # to speed up Dockers builds turn on layer caching
    # which is a paid CircleCI feature
    # https://circleci.com/docs/2.0/docker-layer-caching/
    machine:
      docker_layer_caching: false
    steps:
    - checkout
    - run: docker-compose run --rm e2e
    - store_artifacts:
        path: cypress/screenshots
    - store_artifacts:
        path: cypress/videos

workflows:
  build:
    jobs:
    - e2e
  version: 2