version: 2
jobs:
  build:
    # to speed up Dockers builds turn on layer caching
    # which is a paid CircleCI feature
    # https://circleci.com/docs/2.0/docker-layer-caching/
    machine:
      docker_layer_caching: false
    steps:
    - checkout
    - run: docker-compose build
    - run: docker-compose run --rm e2e

workflows:
  build:
    jobs:
    - build
  version: 2